name: Test
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.0.0

    - name: Validate test dependencies
      run: |
        kubectl version

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make build

    - name: Test
      run: |
        kubectl apply -f example/k8s
        mkdir -p ~/go/bin
        PATH=$PATH:$HOME/go/bin make test test/release
